version: "3.8"

services:
  expressapp:
    image: einesruoka/expressapp
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: expressapp

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=5 # Poll every 5 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower